### ISSUE TITLE
Program aborted by allocation failed when running after 30min.

### ISSUE THREAD

**Issue by woodpenker** [libbpf/blazesym#10]
I flowed the doc to use blazesym's C version to create some libbpf tools. One occasionally crashed by allocation failed, the error msg may like this:
```
memory allocation of 2656 bytes failed
Aborted
```
I checked my c code but found no mem-leak points, and this msg seems to be printed by Rust. So I suspect it comes from this line: https://github.com/libbpf/blazesym/blob/47afb3ddff7de15b6cb03bf945b6d18b711fd9cf/src/lib.rs#L1188

Ref to https://moshg.github.io/rust-std-ja/std/alloc/trait.GlobalAlloc.html#errors, the `alloc` may fail when memory is exhausted and cause abort, am I right? Is it more suitable to check the null pointer and let the user handle this situation?

**Comment by ThinkerYzu1** [comment]
I am curious about how much memory it used.  Is there any memory leaking?  Could you provide details of the process? For example, VSZ/USS/RSS.

**Comment by ThinkerYzu1** [comment]
I just made a patch to give the caller a chance to handle it.  However, according to the manual, the allocator may abort without a return.  Please check the patch if you can reproduce it.

**Comment by ThinkerYzu1** [comment]
> Sorry for the delay in getting back to you. I can't reproduce it every time, so this is just a guess, I will let you know if it happens again with this fix.
No worries! Thank you for reporting this issue.
> 
> Thanks for the advice, I call `blazesym_free()` only when the whole program exit like [this](https://github.com/libbpf/libbpf-bootstrap/blob/a7c0f7e4a286c6c8ba39e8fc736609412fa2de43/examples/c/profile.c#L217), The `symbolizer` is a global var, is that correct?
`Symbolizer` is not a global variable.  you may have multiple instances with different features enabled or for different threads.

**Comment by woodpenker** [comment]
> > Sorry for the delay in getting back to you. I can't reproduce it every time, so this is just a guess, I will let you know if it happens again with this fix.
> > No worries! Thank you for reporting this issue.
> > Thanks for the advice, I call `blazesym_free()` only when the whole program exit like [this](https://github.com/libbpf/libbpf-bootstrap/blob/a7c0f7e4a286c6c8ba39e8fc736609412fa2de43/examples/c/profile.c#L217), The `symbolizer` is a global var, is that correct?
> > `Symbolizer` is not a global variable.  you may have multiple instances with different features enabled or for different threads.

Finally, we found the root cause of the mem leak, it was NOT due to blazesym but some code dependency we wrote. Sorry for making so much noise here. And thanks again for the enhancement of this wonderful lib!
