### ISSUE TITLE
Migrate from `log` to `tracing`

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#209]
We likely want to migrate over to [`tracing`](https://crates.io/crates/tracing), as it provides spans, which help in providing necessary context to log statements. For our intents and purposes, both are pretty much source compatible and so the switch should be close to trivial (even more so given how few log statements we have to begin with).

**Comment by mdrokz** [comment]
> We likely want to migrate over to [`tracing`](https://crates.io/crates/tracing), as it provides spans, which help in providing necessary context to log statements. For our intents and purposes, both are pretty much source compatible and so the switch should be close to trivial (even more so given how few log statements we have to begin with).

Hey can i work on this issue ?

**Comment by danielocfb** [comment]
> Thank you so i went through the codebase and we want to add `#[tracing::instrument]` to the logged methods right ?

I think that would be a good second step and would require identifying relevant call sites and then also mocking the macro when `tracing` is not in use (we should keep the optionality we currently have with the `log` feature).

The first step is mostly just swapping out `::log::` imports with `::tracing::` and setting the appropriate features for the `test-log` dependency (at least that's what I can think of right now), I think.

**Comment by mdrokz** [comment]
> > > Hey can i work on this issue ?
> > 
> > 
> > Absolutely. Let me know if you have any questions, happy to provide guidance.
> 
> Thank you so i went through the codebase and we want to add `#[tracing::instrument]` to the logged methods right ?

and also 

> > Thank you so i went through the codebase and we want to add `#[tracing::instrument]` to the logged methods right ?
> 
> I think that would be a good second step and would require identifying relevant call sites and then also mocking the macro when `tracing` is not in use (we should keep the optionality we currently have with the `log` feature).
> 
> The first step is mostly just swapping out `::log::` imports with `::tracing::` and setting the appropriate features for the `test-log` dependency (at least that's what I can think of right now), I think.

Makes sense let me get started on it

**Comment by danielocfb** [comment]
This issue is completed with https://github.com/libbpf/blazesym/pull/213 merged. Thanks again for your contribution!
