### ISSUE TITLE
Infer build ID section based on section type

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#215]
We should address the following TODO:

https://github.com/libbpf/blazesym/blob/d4ff9f0ee6c31889f36e30312394a869e4126221/src/normalize/normalizer.rs#L66-L70

Should be a straight forward and isolated change, easy to test.

**Comment by matthew-olson-intel** [comment]
I'll work on this. Looking at `readelf`, it should be a simple process of iterating over all section headers and checking for type `SHT_NOTE`, and then iterating over the program headers and looking for the `PT_NOTE` type.
