### ISSUE TITLE
Add `*_sorted` variants of symbolization APIs

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#224]
We should add `*_sorted` variants similar to what we have for the address normalization APIs
https://github.com/libbpf/blazesym/blob/21498b6667d13a8784488ece8e57a5ab66717c3c/src/normalize/normalizer.rs#L358-L378

to the symbolization logic here:
https://github.com/libbpf/blazesym/blob/21498b6667d13a8784488ece8e57a5ab66717c3c/src/symbolize/symbolizer.rs#L208-L210

That would mean introducing and implementing such a new function, adding tests, and exposing it through C bindings.

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by d-e-s-o** [comment]
> I'd like to look into this.

Awesome! Please let me know if you have any questions.

**Comment by danielocfb** [comment]
@tarunsamanta2k20 do you need any help with this task?

**Comment by tarunsamanta2k20** [comment]
Let me do it.

**Comment by tarunsamanta2k20** [comment]
Let me check once.

**Comment by d-e-s-o** [comment]
I looked at this and while it's certainly possible to implement and conceptually makes sense, in reality the performance benefit is probably miniscule, given that symbolization itself is not cheap and sorting a few addresses is unlikely to move the needle. And it really only provides a benefit for process symbolization anyway. Let's put this task on hold until we have a true need, given the anticipated increase in code complexity.
