### ISSUE TITLE
Use `/tmp/perf-[pid].map`

### ISSUE THREAD

**Issue by TimPushkin** [libbpf/blazesym#256]
perf uses data from `/tmp/perf-[pid].map` files to symbolize stack traces -- this is required for JIT-ed languages to update the mappings dynamically. There are tools for such languages for generating these files, e.g. [`jcmd <java-pid> Compiler.perfmap`](https://docs.oracle.com/en/java/javase/20/docs/specs/man/jcmd.html) or [perf-map-agent](https://github.com/jvm-profiling-tools/perf-map-agent) for Java. It would be great if blazesym used these perf map files when symbolizing addresses for a process.

**Comment by d-e-s-o** [comment]
I was just looking at what `bcc` supports in terms of symbolization, and it seems it supports perf maps as well. E.g., https://github.com/iovisor/bcc/blob/1a784cfe1a2936f2c5cf0a8ee045dcdfd841ba5f/src/cc/bcc_perf_map.c

**Comment by d-e-s-o** [comment]
This seems to be the "documentation": https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/Documentation/jit-interface.txt

**Comment by d-e-s-o** [comment]
@TimPushkin this support is available now. Feel free to give it a try.
