### ISSUE TITLE
inspect: Provide access to all discovered symbols

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#284]
As it stands, the [`inspect`](https://docs.rs/blazesym/0.2.0-alpha.3/blazesym/inspect/index.html) API and its `Inspector` type specifically only support targeted symbol lookup by name. For some use cases it may be necessary to know all available symbols *in advance*. We should extend the API to support such use case.

**Comment by d-e-s-o** [comment]
I have this close to ready over in https://github.com/danielocfb/blazesym/tree/topic/inspector. Should be out for review tomorrow.

**Comment by d-e-s-o** [comment]
Included in https://github.com/libbpf/blazesym/pull/389.
