### ISSUE TITLE
inspect: Proper file offset reporting for DWARF

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#285]
Currently file offsets are not reported [correctly](https://github.com/libbpf/blazesym/blob/bb352528ce3c427a70861901426e82148292763e/src/dwarf/resolver.rs#L194) when using DWARF. DWARF does not carry file offset information from what I understand, but we can bridge the gap by looking up the address of the symbol and then mapping that address to a file offset. The problem is that we need the complete ELF file for doing so. Even without true split-DWARF support, there is no requirement a DWARF file contain ELF bits necessary for running, so we may need to require additional information (path to the ELF file) from the user.

**Comment by d-e-s-o** [comment]
I don't think the above is correct, actually. We do [fix up](https://github.com/libbpf/blazesym/blob/bb352528ce3c427a70861901426e82148292763e/src/inspect/inspector.rs#L77) the offset at a later step in the process, but it's confusing. This will be cleaned up once we land https://github.com/danielocfb/blazesym/commit/86333165e92d6643e0bc605147c7f21cae5d66f5 or similar.

This doesn't address the split-debug info situation, but we do not support that at this point so it's not an actual concern and more something to keep in mind moving forward..
