### ISSUE TITLE
unsoundness in `extract_string` function

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#31]
```rust
pub fn extract_string(raw: &[u8], off: usize) -> Option<&str> {
    let mut end = off;

    if off >= raw.len() {
        return None;
    }
    while raw[end] != 0 {
        end += 1;
    }
    let blk = raw[off..end].as_ptr() as *mut u8;
    let r = unsafe { String::from_raw_parts(blk, end - off, end - off) };
    let ret = Some(unsafe { &*(r.as_str() as *const str) }); // eliminate lifetime
    r.into_bytes().leak();
    ret
}
```
The function's implementation seems broken. First off, it should document safety invariants upheld in `unsafe` blocks with [`SAFETY` comments](https://std-dev-guide.rust-lang.org/documentation/safety-comments.html#safety-comments). For `String::from_raw_parts`, these read:
```
    /// # Safety
    ///
    /// This is highly unsafe, due to the number of invariants that aren't
    /// checked:
    ///
    /// * The memory at `buf` needs to have been previously allocated by the
    ///   same allocator the standard library uses, with a required alignment of exactly 1.
    /// * `length` needs to be less than or equal to `capacity`.
    /// * `capacity` needs to be the correct value.
    /// * The first `length` bytes at `buf` need to be valid UTF-8.
    ///
    /// Violating these may cause problems like corrupting the allocator's
    /// internal data structures. For example, it is normally **not** safe to
    /// build a `String` from a pointer to a C `char` array containing UTF-8
    /// _unless_ you are certain that array was originally allocated by the
    /// Rust standard library's allocator.
    ///
    /// The ownership of `buf` is effectively transferred to the
    /// `String` which may then deallocate, reallocate or change the
    /// contents of memory pointed to by the pointer at will. Ensure
    /// that nothing else uses the pointer after calling this
    /// function.
```

Evaluating these:
- The memory at `buf` needs to have been previously allocated by the same allocator the standard library uses, with a required alignment of exactly 1.
  - this is with almost 100% certainty violated: the memory has not been allocated with the standard allocator; it's also not communicated to callers in any way. So at best this function is unsound and a ticking time bomb, but most likely plain undefined behavior.
- `capacity` needs to be the correct value
  - Questionable; could be the case but unlikely. Again, unsoundness at the very least as it's certainly not ensured/enforced anywhere.
- The first `length` bytes at `buf` need to be valid UTF-8
  - not ensured anywhere. Again, callers may randomly uphold this invariant, but in all likelihood it's violated in all but a few places that got lucky. It's also not communicated to callers in any way.

**Comment by ThinkerYzu1** [comment]
The allocator part is not right.  This function returns a reference, not an owned object.  So, there is no allocation or deallocation involved here.

For invalid UTF-8 code points, we need to handle them by either encoding them or skipping them.

**Comment by danielocfb** [comment]
> The allocator part is not right. This function returns a reference, not an owned object. So, there is no allocation or deallocation involved here.

It does not matter what the function returns. What matters is what functions are called inside it.

**Comment by ThinkerYzu1** [comment]
Are you saying `String::from_raw_parts(...)`?

**Comment by ThinkerYzu1** [comment]
According to the document.
> This is highly unsafe, due to the number of invariants that aren’t checked:
> ....
So, it is why `from_raw_parts()` is unsafe.  That is why `leak()` is there as a hack to avoid corruption.
However, moving to `CStr` is a better solution.

**Comment by danielocfb** [comment]
> According to the document.
> 
> > This is highly unsafe, due to the number of invariants that aren’t checked:
> > ....
> 
> So, it is why `from_raw_parts()` is unsafe. That is why `leak()` is there as a hack of these _unchecked_ to avoid corruption. However, moving to `CStr` is a better solution.

Unfortunately, that's not how it works. You call the function you have to adhere to the constraints it imposes at the time you call it.
