### ISSUE TITLE
API for single address symbolization

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#317]
We may want to expose an API for symbolizing a single address. It would be more convenient than dealing with a `Vec` in some cases and it would not necessitate an allocation.

cc @salvatorebenedetto

**Comment by anakryiko** [comment]
symbolizing multiple addresses in a batched mode should be much faster, though? So for symbolizing stack traces and such, batched API is much more preferred

**Comment by salvatorebenedetto** [comment]
> symbolizing multiple addresses in a batched mode should be much faster, though? So for symbolizing stack traces and such, batched API is much more preferred

Not in the case of offline symbolication as it is implemented today. When callling `symbolize` with `Source::Elf` you can pass a [single ELF path](https://github.com/libbpf/blazesym/blob/main/src/symbolize/source.rs#L200) so you call it for the whole stacktrace.

**Comment by d-e-s-o** [comment]
> > symbolizing multiple addresses in a batched mode should be much faster, though? So for symbolizing stack traces and such, batched API is much more preferred
> 
> Not in the case of offline symbolication as it is implemented today. When callling `symbolize` with `Source::Elf` you can pass a [single ELF path](https://github.com/libbpf/blazesym/blob/main/src/symbolize/source.rs#L200) so you can't call it for the whole stacktrace.

I think you'd want to post-process it and group by ELF file each address falls in and then use batched mode, unless you don't care about performance. It's an orthogonal problem, though, and I think we should support the single address case for the reasons outlined in the motivation above: it can't be done more convenient and cheaply *for a single address* using the existing API and so it's reasonable for the library to provide such an API, irrespective of whether it is the best solution in all cases.
