### ISSUE TITLE
Move C API into separate crate?

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#344]
I haven't prototyped any of it or thought it through completely, but I think we should consider moving everything making up the C API into a separate (in-workspace) crate, `blazesym-c` (or similar). That would allow us to version the two independently and while I don't think we will make use of that capability anytime soon, it seems cleaner and potentially useful down the line.
Focusing the C bits elsewhere has other benefits such as easily linkable documentation, reduced compile time of the main crate, etc.

**Comment by anakryiko** [comment]
Makes sense, assuming it's easy to keep them in sync and prevent accidental blazesym-c breakage?

**Comment by danielocfb** [comment]
> Makes sense, assuming it's easy to keep them in sync and prevent accidental blazesym-c breakage?

I think so; they would be in the same repository and workspace and so once you change one the other would see changes.

**Comment by danielocfb** [comment]
There seems to be precedent for such a split:
https://github.com/rust-lang/rustc-demangle#usage-from-non-rust-languages
https://github.com/rust-lang/rustc-demangle/tree/main/crates/capi

**Comment by danielocfb** [comment]
I started [prototyping](https://github.com/danielocfb/blazesym/tree/topic/capi-crate) this proposal but it turns out the issue is that because our Rust API declares a bunch of types as non-exhaustive, once we cross crate boundaries we are running into issues constructing the corresponding objects. We could probably work around that somehow with special cases and whatnot, but at least at this point it's unlikely to be worth the trouble.

I'll keep the code around, should I come up with a good solution, but we can probably declare this proposal as failed-at-prototype-stage.

**Comment by d-e-s-o** [comment]
Reopening this as I keep coming back to wanting the separation.
