### ISSUE TITLE
Failed to build on arm64 platform

### ISSUE THREAD

**Issue by pomeloos** [libbpf/blazesym#494]
I attempted to build on the arm64 platform ubuntu22.04, but encountered an error:
$ cargo build -v
   Compiling libc v0.2.152
   Compiling cpp_demangle v0.4.3
       Fresh equivalent v1.0.1
       Fresh hashbrown v0.14.3
       Fresh cfg-if v1.0.0
       Fresh stable_deref_trait v1.2.0
       Fresh fallible-iterator v0.3.0
       Fresh rustc-demangle v0.1.23
     Running `/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name build_script_build /home/pomelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=147 --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=cc048ea372572551 -C extra-filename=-cc048ea372572551 --out-dir /home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551 -L dependency=/home/pomelo/blazesym/target/debug/deps --cap-lints allow`
     Running `/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name build_script_build --edition=2018 /home/pomelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpp_demangle-0.4.3/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=147 --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ae6f72659279d9ce -C extra-filename=-ae6f72659279d9ce --out-dir /home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce -L dependency=/home/pomelo/blazesym/target/debug/deps --cap-lints allow`
   Compiling indexmap v2.1.0
     Running `/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name indexmap --edition=2021 /home/pomelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.1.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=147 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=90791bf4016cd737 -C extra-filename=-90791bf4016cd737 --out-dir /home/pomelo/blazesym/target/debug/deps -L dependency=/home/pomelo/blazesym/target/debug/deps --extern equivalent=/home/pomelo/blazesym/target/debug/deps/libequivalent-b3bb5ce6a6ccea72.rmeta --extern hashbrown=/home/pomelo/blazesym/target/debug/deps/libhashbrown-312ed446183dcaa8.rmeta --cap-lints allow`
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/pomelo/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "cc" "/tmp/rustcjh8iNK/symbols.o" "/home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551/build_script_build-cc048ea372572551.build_script_build.b5138d19f7ae161a-cgu.0.rcgu.o" "/home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551/build_script_build-cc048ea372572551.build_script_build.b5138d19f7ae161a-cgu.1.rcgu.o" "/home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551/build_script_build-cc048ea372572551.build_script_build.b5138d19f7ae161a-cgu.2.rcgu.o" "/home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551/build_script_build-cc048ea372572551.build_script_build.b5138d19f7ae161a-cgu.3.rcgu.o" "/home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551/build_script_build-cc048ea372572551.4k57d5xbghnvr0cn.rcgu.o" "-Wl,--as-needed" "-L" "/home/pomelo/blazesym/target/debug/deps" "-L" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd-ff9e2f4daa5f5044.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libpanic_unwind-4c069e5be14e089e.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libobject-5dad8c6832fe5ee1.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libmemchr-08fa975fabbb7847.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libaddr2line-6fa5c572933bd83c.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libgimli-29e75079cbe951ff.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_demangle-770a536d7b802f6e.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd_detect-828e977783680240.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libhashbrown-c2f157ffd03af249.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-07044d868b568254.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libminiz_oxide-b9447ffb1c9d5ec5.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libadler-287e4034a78ea916.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libunwind-c821617a29de84b3.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcfg_if-077e039e6f0bd75d.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/liblibc-27cd7f142906ea75.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/liballoc-55c809a1b2d51fd2.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_std_workspace_core-fc61da4cf34b1cd0.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcore-ead1225e03eb63b1.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-3f410048cea510b6.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551/build_script_build-cc048ea372572551" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /tmp/rustcjh8iNK/symbols.o: file not recognized: file format not recognized
          collect2: error: ld returned 1 exit status
          

error: could not compile `libc` (build script) due to previous error

Caused by:
  process didn't exit successfully: `/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name build_script_build /home/pomelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.152/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=147 --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=cc048ea372572551 -C extra-filename=-cc048ea372572551 --out-dir /home/pomelo/blazesym/target/debug/build/libc-cc048ea372572551 -L dependency=/home/pomelo/blazesym/target/debug/deps --cap-lints allow` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/pomelo/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "cc" "/tmp/rustcxIakZ3/symbols.o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce.build_script_build.1f8e36547c7e6d89-cgu.0.rcgu.o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce.build_script_build.1f8e36547c7e6d89-cgu.1.rcgu.o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce.build_script_build.1f8e36547c7e6d89-cgu.2.rcgu.o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce.build_script_build.1f8e36547c7e6d89-cgu.3.rcgu.o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce.build_script_build.1f8e36547c7e6d89-cgu.4.rcgu.o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce.2snuwfwc7wafm55a.rcgu.o" "-Wl,--as-needed" "-L" "/home/pomelo/blazesym/target/debug/deps" "-L" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd-ff9e2f4daa5f5044.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libpanic_unwind-4c069e5be14e089e.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libobject-5dad8c6832fe5ee1.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libmemchr-08fa975fabbb7847.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libaddr2line-6fa5c572933bd83c.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libgimli-29e75079cbe951ff.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_demangle-770a536d7b802f6e.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd_detect-828e977783680240.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libhashbrown-c2f157ffd03af249.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-07044d868b568254.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libminiz_oxide-b9447ffb1c9d5ec5.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libadler-287e4034a78ea916.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libunwind-c821617a29de84b3.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcfg_if-077e039e6f0bd75d.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/liblibc-27cd7f142906ea75.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/liballoc-55c809a1b2d51fd2.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_std_workspace_core-fc61da4cf34b1cd0.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcore-ead1225e03eb63b1.rlib" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-3f410048cea510b6.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce/build_script_build-ae6f72659279d9ce" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /tmp/rustcxIakZ3/symbols.o: file not recognized: file format not recognized
          collect2: error: ld returned 1 exit status
          

error: could not compile `cpp_demangle` (build script) due to previous error

Caused by:
  process didn't exit successfully: `/home/pomelo/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name build_script_build --edition=2018 /home/pomelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpp_demangle-0.4.3/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=147 --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ae6f72659279d9ce -C extra-filename=-ae6f72659279d9ce --out-dir /home/pomelo/blazesym/target/debug/build/cpp_demangle-ae6f72659279d9ce -L dependency=/home/pomelo/blazesym/target/debug/deps --cap-lints allow` (exit status: 1)

**Comment by d-e-s-o** [comment]
As it says, `libc` and `cpp_demangle` fail to compile, so it doesn't seem like an issue with `blazesym`.

In general, though, the error
> file not recognized: file format not recognized

would suggest to me that something may be amiss with your cross compile setup, assuming that's what you have. I would check `file /tmp/rustcxIakZ3/symbols.o` and see what it says.

**Comment by d-e-s-o** [comment]
Not a `blazesym` issue.
