### ISSUE TITLE
Unable to get function name from c++ binary

### ISSUE THREAD

**Issue by r1viollet** [libbpf/blazesym#503]
# Description

I was unable to symbolize some amount of addresses. I attached a binary where I experimented on plugging blazesym. If it is useful I can provide build commands.
From the binary attached you can retrieve the symbols
```
nm ./ddprof | grep "ae1a0 T main"
00000000000ae1a0 T main
```
Then try to symbolize it
```
blazecli symbolize elf --path ./ddprof 00000000000ae1a0
0x000000000ae1a0:  @ 0xae1a0+0x0 /home/r1viollet/dd/ddprof/src/exe/main.cc:381:34
```
Location and file are good, though function name is not found. I would expect the symbol table to have that information (as per nm command)

[ddprof.zip](https://github.com/libbpf/blazesym/files/14098449/ddprof.zip)

**Comment by d-e-s-o** [comment]
Thanks for the report! That seems to be an oversight in the DWARF parsing code from the looks of it. Will work on getting it fixed, but may take a few days.

**Comment by d-e-s-o** [comment]
@r1viollet okay, so I got it working with https://github.com/danielocfb/blazesym/tree/topic/dwarf-refs This will need a bit more work before land, but it should unblock you.

```
$ cargo run -p blazecli -- symbolize elf --path /tmp/ddprof 0xae1a0
> 0x000000000ae1a0: main @ 0xae1a0+0x0 /home/r1viollet/dd/ddprof/src/exe/main.cc:381:34
```
