### ISSUE TITLE
Unprivileged normalize API 

### ISSUE THREAD

**Issue by r1viollet** [libbpf/blazesym#518]
# Description

When using the current normalize API, we require elevated permissions. This is due to the usage of map_files.
Here is for instance the failing syscall from a strace:
```
4122778 openat(AT_FDCWD, "/proc/4122778/map_files/61bc0125c000-61bc0125e000", O_RDONLY|O_CLOEXEC) = -1 EPERM (Operation not permitted)
```
We could propose a normalization API that works from source.
The logic would be similar to what we propose [here](https://github.com/DataDog/ddprof/blob/0a0dfa3e5ea7ea9f6587865736bd80cedd010674/src/ddprof_module_lib.cc#L81-L86) 

This uses the mapping information (from `proc/<PID>/maps`) and the segment information from the file. Finding files associated to mappings can be a challenge. So perhaps it should be the responsibility of the user, to provide the matching elf file.

# Motivation

This would allow us to use the API within a process (or a child process) to symbolize itself (or the parent).
Our use case is to annotate crashes or errors with associated symbols. From the associated stack trace, we could normalize and symbolize from source.

**Comment by r1viollet** [comment]
This is somewhat a different use case from the issues I previously submitted. Thanks again for being so fast in reacting and answering my issues.

**Comment by d-e-s-o** [comment]
Yeah, I can see it being useful to have a solution for cases where fewer permissions are available. We changed this behavior with 327f2884205d5f3e7b24dc8b06f9bd9a40d71f2f and effectively requiring `root` has certainly not been a great characteristic to have ever since.

> We could propose a normalization API that works from source.

What are you referring to when you say "from source"?

We still keep what we call the symbolic path around, so we could introduce an option to use that instead of the `maps_file`. I can't think of a better API design off-hand.

**Comment by d-e-s-o** [comment]
@r1viollet I created https://github.com/libbpf/blazesym/pull/520, which I'd think should cater to your use case by setting the `map_files` argument to `false` in the `blaze_symbolize_src_process` object. Feel free to give it a try and let us know if it works for you.

**Comment by d-e-s-o** [comment]
Closed via https://github.com/libbpf/blazesym/commit/8415b4e3a3439b4cefb82f1f516041c426d92a33

**Comment by r1viollet** [comment]
Sorry for the late feedback. I was out for some days. This worked well for us! Thank you :bow:
