### ISSUE TITLE
Error symbolizing Go binaries

### ISSUE THREAD

**Issue by r1viollet** [libbpf/blazesym#581]
# Description

I have hit some issues while symbolizing Go binaries. Here is an example I could reproduce with several Go binaries:
You can build a quick hello world program to reproduce the issue.

```
nm main | grep runtime.rt0_go.abi0
  000000000045aac0 T runtime.rt0_go.abi0
blazecli symbolize elf --path ./main 000000000045aac0  
  Error: failed to symbolize addresses

Caused by:
    Hit the end of input before it was expected
```

**Comment by r1viollet** [comment]
For reproduction any binary should do. Here is a simple hello world.
```
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```
Then build the example:
```
go build main.go
```
You should not be able to symbolize associated symbols.

**Comment by r1viollet** [comment]
I am curious as to why the elf resolver would have trouble with Go binaries. Feel free to reach out if I can help with repro / other cases.

**Comment by r1viollet** [comment]
This could be dwarf related: --no-debug-syms allows us to get the symbol.
```
blazecli symbolize elf --no-debug-syms --path ./main "000000000045aac0"
0x0000000045aac0: runtime.rt0_go.abi0 @ 0x45aac0+0x0
```

**Comment by nsavoire** [comment]
I think the root cause of the failure is the presence of compressed debug section in the binary.
I reproduce the issue with a simple C program compiled with compressed debug section:
```
// test.c
 __attribute__((noinline)) void foo() {
  while (1) {}
}

int main() {
  foo();
}
```

```
gcc -g test.c -o test -gz=zlib
```

**Comment by d-e-s-o** [comment]
> I think the root cause of the failure is the presence of compressed debug section in the binary.

Interesting. Yes, we do not currently support compressed debug sections and Go seems to have enabled them by default from what I understand.
I am still occupied wrapping up other work, but will look hopefully be able to take a closer look by Friday.

**Comment by danielocfb** [comment]
So I didn't have much time to look at it, but I suspect we need two things. First, support for dealing with compressed ELF headers. I think that should be reasonably straight forward to add. Then, presumably we'd decompress the data on the fly while reading -- that should also not be that much, though it could be a bit problematic that we currently rely on memory mapping everywhere and that could translate to large allocations. So ideally we'd rework those bits eventually to support more gradual/on demand reads. What I haven't gotten to is what, if anything, needs to happen on the DWARF side of things. I've certainly come across special section names being used, but there could be more. Will have more time to look into it next week.

**Comment by r1viollet** [comment]
I would find the first approach of just decompressing on the fly very valuable. I think users can expect some overhead when they ask for debug information.

On ideas to support more gradual reads, one thing I noticed was that when only asking for location information (without inlining), we seem to be paying the cost of more than just the debug_line section. I think the gimli dwarf loader just opens all of the dwarf it can find. I think I was seeing an 80 megs difference symbolizing an Envoy binary with debug information (and requesting code locations, no inlining info).

I think the gradual reads would be nice. Though the information for inlined functions are scattered around in the debug info section (afaik), so we would still pay a significant cost when parsing these. That seems like a generally hard thing to optimize.

**Comment by d-e-s-o** [comment]
All that being said, I opened https://github.com/libbpf/blazesym/pull/590 which should add the necessary support. Feel free to give it a try. Right now it only supports zlib compression. Let me know if you need zstd as well and I should be able to add it quickly.

**Comment by javierhonduco** [comment]
Just wanted to say thank you for opening the issue and @d-e-s-o for very quickly implementing the feature! Been using blazesym in a new project and so far things have been super smooth. Go symbolization was the only thing I found missing!
