### ISSUE TITLE
List supported features

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#59]
We should have some kind of outline of what features we support and which ones are planned/work in progress in the README, so that users don't have to rely on trial and error to figure that out (and/or comb through the code).

**Comment by danielocfb** [comment]
This has pretty much been done as part of the README overhaul b199e9e03bf8ecbdf2e7323cd086a3013ea0ab5b. No concrete other plans to add more, though as we check things off from the list we may consider adding them to another one explicitly  mentioning features.

**Comment by d-e-s-o** [comment]
FWIW, I didn't find this issue at the time, but we added something along those lines with https://github.com/libbpf/blazesym/commit/c93ff8d5dd2b4324f53611a85087a1f2de2bd6bb.
