### ISSUE TITLE
Unsoundness in `ElfParser::get_all_program_headers()` function

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#63]
https://github.com/libbpf/blazesym/blob/fde205278aba4874eda69cdb179988abfb7ec3bd/src/elf/parser.rs#L566-L575

The function creates a mutable reference from a shared context. That means we can end up with multiple "exclusive" references to the same object, which is not allowed.

**Comment by d-e-s-o** [comment]
Similar issue seems to exist here: https://github.com/libbpf/blazesym/blob/fde205278aba4874eda69cdb179988abfb7ec3bd/src/elf/parser.rs#L542
