### ISSUE TITLE
how can I get elf type using c api

### ISSUE THREAD

**Issue by lemon0910** [libbpf/blazesym#644]
I can get elf type like:

readelf -h profile

ELF Header:

  Type:                              DYN (Position-Independent Executable file)

It's very important to convert address to symbol.

but I read c api document https://docs.rs/blazesym-c/latest/blazesym_c/fn.blaze_inspect_syms_elf.html, I don't find api to get the type of elf files

**Comment by d-e-s-o** [comment]
Can you elaborate on your workflow, what you are trying to achieve, and why the ELF type would have relevance for that?

**Comment by lemon0910** [comment]
I write a progarm like profile (https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/profile.c).

I want to profile c++ program. 

The c++ program split debuginfo from binary : objcopy --only-keep-debug my_program my_program.debug

so I need:
1, call bpf_get_stack to get stack function adress.
2, convert function address to symbol using debuginfo.

In pharse 2, different elf type like ET_DYN or ET_EXEC have different way to convert. 

For ET_EXEC type, I can directly convert using blaze_symbolize_elf_virt_offsets

For ET_DYN type, I need call blaze_normalize_user_addrs before blaze_symbolize_elf_virt_offsets

**Comment by d-e-s-o** [comment]
> different elf type like ET_DYN or ET_EXEC have different way to convert.

I don't believe that is true, the mechanism is the same for all types.

> For ET_EXEC type, I can directly convert using blaze_symbolize_elf_virt_offsets

`bpf_get_stack` should report absolute addresses, so you'd need process symbolization, which also normalizes addresses, in both cases. Yes, `blaze_symbolize_elf_virt_offsets` may work in some cases, but it's still not right.

Split debug info support has not yet been implemented for `blazesym` (https://github.com/libbpf/blazesym/issues/60). That being said, the `objcopy` way you outline above is basically just producing "regular" DWARF from what I understand -- just not inside the executable file itself. So you should be able to symbolize it once https://github.com/libbpf/blazesym/pull/634 lands: set a custom process dispatch function and then return an `ElfResolver` working on `my_program my_program.debug`.

**Comment by danielocfb** [comment]
> So you should be able to symbolize it once #634 lands: set a custom process dispatch function and then return an `ElfResolver` working on `my_program my_program.debug`.

That change has landed.

Direct debug link support is out as well: https://github.com/libbpf/blazesym/pull/665
