### ISSUE TITLE
DWARF source code line reporting not working

### ISSUE THREAD

**Issue by d-e-s-o** [libbpf/blazesym#68]
Source code line reporting does not appear to be working properly for DWARF. Assuming https://github.com/libbpf/blazesym/pull/67, I add
```patch
--- tests/blazesym.rs
+++ tests/blazesym.rs
@@ -54,4 +54,5 @@ fn symbolize_dwarf() {

     let result = results.first().unwrap();
     assert_eq!(result.symbol, "factorial");
+    assert_eq!(result.line_no, 7);
 }
```
And the assertion fails:
```
---- symbolize_dwarf stdout ----
thread 'symbolize_dwarf' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `7`', tests/blazesym.rs:56:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Yet, the file seems to contain the proper information:
```
$ llvm-dwarfdump --name=factorial data/test-dwarf.bin
data/test-dwarf.bin:    file format elf64-x86-64

0x000000a3: DW_TAG_subprogram
              DW_AT_external    (true)
              DW_AT_name        ("factorial")
              DW_AT_decl_file   ("data/test-stable-addresses.c")
              DW_AT_decl_line   (7)
              DW_AT_decl_column (0x01)
              DW_AT_prototyped  (true)
              DW_AT_type        (0x000000d3 "unsigned int")
              DW_AT_low_pc      (0x0000000002000100)
              DW_AT_high_pc     (0x000000000200012b)
              DW_AT_frame_base  (DW_OP_call_frame_cfa)
              DW_AT_GNU_all_tail_call_sites     (true)
              DW_AT_sibling     (0x000000d3)
```

**Comment by matthew-olson-intel** [comment]
Is this issue solved?  I tried reproducing, and the assertion succeeds-- it finds that `factorial` was defined on line 8 of `test-stable-addresses.c`.

**Comment by d-e-s-o** [comment]
> Is this issue solved? I tried reproducing, and the assertion succeeds-- it finds that `factorial` was defined on line 8 of `test-stable-addresses.c`.

Interesting. It still does not work for me. I haven't looked into it, though.

**Comment by matthew-olson-intel** [comment]
No problem: I'll just mail you my laptop, and then it'll work for both of us!

**Comment by d-e-s-o** [comment]
> No problem: I'll just mail you my laptop, and then it'll work for both of us!

;-) Could you attach `data/test-dwarf.bin`, then I could compare binaries. I suspect this will all get addressed once we switch to `gimli`, which hopefully is not so far out anymore at this point.

**Comment by matthew-olson-intel** [comment]
Realized that I was going by the line numbers in your original `diff`, which at the present moment is in `symbolize_gsym`, so wasn't testing `symbolize_dwarf` at all.  Same result as you now.

Is this worth focusing on, if we'll use `gimli` soon?

**Comment by danielocfb** [comment]
Ah, that explains it. Thanks!

> Is this worth focusing on, if we'll use `gimli` soon?

I was just curious if there was some non-deterministic behavior causing it to work on your system but not mine that I'd have wanted to investigate. But given that as you state it's not working for you either it's probably best to just wait for the `gimli` conversion.

**Comment by matthew-olson-intel** [comment]
The root of the problem is that `ElfCacheEntry::new` calls `DwarfResolver::from_parser_for_addresses` with an empty `addresses` argument (https://github.com/libbpf/blazesym/blob/a40d9478c0a51ddd2484c67ffcb53c387d9ac4d1/src/elf/cache.rs#L61).  That function never gets called again, so `DwarfResolver::addr_to_dlcu`, and thus `DwarfResolver::debug_line_cus` is always empty.

**Comment by d-e-s-o** [comment]
Oh nice, thanks for digging into it! Feel free to open a PR if you have a fix in mind. Otherwise I'll look into it soon.

**Comment by d-e-s-o** [comment]
So it seem the empty addresses stuff is actually fine: the semantics are that if no addresses are provided, all line information is gathered. The problem is more that we see an invalid extended op code, can't handle it, and then swallow the error (!!!).

> invalid extended opcode (ip=0x23, insn_size=0x0)

So yes, this will need to wait until we transition to `gimli`...

**Comment by matthew-olson-intel** [comment]
Ach, you're right. I briefly looked into debugging it, but I've no experience with the DWARF FSM: definitely worth waiting for `gimli`.
