### ISSUE TITLE
CU's start address should be in strict order: [6] 0x84700 [7] 0x84700

### ISSUE THREAD

**Issue by woodpenker** [libbpf/blazesym#8]
When using this lib's C version, I meat this panic error
```
thread '<unnamed>' panicked at 'CU's start address should be in strict order: [6] 0x84700 [7] 0x84700', src/dwarf.rs:802:9
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted
```

It seems caused by https://github.com/libbpf/blazesym/blob/47afb3ddff7de15b6cb03bf945b6d18b711fd9cf/src/dwarf.rs#L898, how to solve this?

version: 885b4d5297c1633444317d439b312626920b5486

**Comment by ThinkerYzu1** [comment]
This check seems unnecessary since the data has been sorted now and the check is too restricted. We are going to return multiple lines for an address. So, there is no reason that two or more CU starts at the same address.

**Comment by ThinkerYzu1** [comment]
@woodpenker could you confirm that pull #9 fixes your issue?

**Comment by woodpenker** [comment]
> @woodpenker could you confirm that pull #9 fixes your issue?

Yes, this PR fixes my issue.
