### ISSUE TITLE
Fully support handling of kernel addresses

### ISSUE THREAD

**Issue by jfernandez** [libbpf/blazesym#806]
The README states: `currently normalization APIs, for example, only support user space addresses`.

What is the current status for symbolizing kernel addresses? From my experimentation, I do see some symbols for kernel stack traces.

**Comment by d-e-s-o** [comment]
Symbolization should work for core-kernel addresses using `kallsyms` or regular ELF/DWARF symbols if you specify the kernel image path or `blazesym` can find it. It should work for kernel module addresses if they are present in `kallsyms` (no ELF/DWARF there). There is no support for BPF programs, VDSOs, etc. Normalization support hasn't been designed yet.

**Comment by jfernandez** [comment]
@d-e-s-o, thank you for the clarification. 

> Symbolization should work for core-kernel addresses using kallsyms or regular ELF/DWARF symbols if you specify the kernel image path or blazesym can find it.

How does `blazesym` decide to use the kernel image over `kallsyms`? And I'm assuming you mean here a `vmlinux` file.

**Comment by danielocfb** [comment]
> @d-e-s-o, thank you for the clarification.
> 
> > Symbolization should work for core-kernel addresses using kallsyms or regular ELF/DWARF symbols if you specify the kernel image path or blazesym can find it.
> 
> How does `blazesym` decide to use the kernel image over `kallsyms`? And I'm assuming you mean here a `vmlinux` file.

Currently it gives preference to `kallsyms`. I.e., if a symbol is found there it will be reported. ELF acts as a fallback. This is subject to change. Everything else should be available in the [documentation](https://docs.rs/blazesym/0.2.0-rc.0/blazesym/symbolize/struct.Kernel.html#fields).

**Comment by jfernandez** [comment]
@danielocfb thanks for the context!
