### ISSUE TITLE
`Normalizer::normalize_user_addrs_opts` fails in a Docker container

### ISSUE THREAD

**Issue by gleocadie** [libbpf/blazesym#821]
I have a module that collects callstack and it uses blazesym to normalize the instruction pointers. It uses the version `0.2.0-rc.0`

When I run it in a Docker container, the call to `normalize_user_addrs_opts` fails with this error:
```
Failed to stat /proc/11202/map_files/5633a80fc000-5633a8112000
Caused by:
     Operation not permitted (os error 1)
```

The user running my app (which loads my module) is `root`.
After testing and looking on the net, it seems that in Docker container, even reading `/proc/XX/map_files` can also be forbidden to the root user. When starting my container using the `--privileged` flag, it's ok. But my module is destined to run on customer environment where I cannot control the way they run their containers.

I decided to have an instance of `NormalizeOpts` with `map_files` set to `false` and pass it to `normalize_user_addrs_opts`, but I still have the failure.

After debugging, I saw that when `blazesym` tries to [read the build-id](https://github.com/libbpf/blazesym/blob/5a15e2e4f07400eaa6d56453dbbfc9018c386d50/src/normalize/user.rs#L195) it uses the `map_files` instead of the `path`.

I made a local fix (replacing `&entry_path.maps_file` by `path` at line 195) and it works. I do not have the error anymore.

Since I set `map_files` to false, shouldn't the build-id reader use the `symbolic_path` instead ? (like in my local test)

**Comment by d-e-s-o** [comment]
I remember thinking about this case a while back but then coming to the conclusion that the existing behavior was okay. I believe my reasoning was that while it makes sense to report the symbolic path (to have "something" to attach meaning to on the remote system), we'd still want to use the `map_file` entry for the build ID for set of benefits it provides. In my mental model, if you are using symbolic paths you are unlikely to require build IDs as well, so you might as well disable them (which would alleviate this problem as well).

From the sounds of it you require build IDs, though, right? And you only switch to symbolic paths to work around the permission issues. I think it would be fine to switch over to using the symbolic path for the build ID as well. Please feel free to submit a pull request to change the behavior.

**Comment by d-e-s-o** [comment]
Closed by https://github.com/libbpf/blazesym/commit/a76bef827626bcdd6dfb89ab8f688197ce5fd897.
