### ISSUE TITLE
Confusion around output of `normalize_user_addrs`

### ISSUE THREAD

**Issue by nsavoire** [libbpf/blazesym#835]
I am confused by the addresses returned by `Normalizer::normalize_user_addrs`.
From the source documentation of [Output](https://github.com/libbpf/blazesym/blob/v0.2.0-rc.1/src/normalize/normalizer.rs#L36-L45), [module](https://github.com/libbpf/blazesym/blob/v0.2.0-rc.1/src/normalize/mod.rs#L15-L18), and [actual computation](https://github.com/libbpf/blazesym/blob/v0.2.0-rc.1/src/normalize/user.rs#L169), return addresses are definitely file offsets.

On the other hand, [Normalizer source doc](https://github.com/libbpf/blazesym/blob/v0.2.0-rc.1/src/normalize/normalizer.rs#L161-L166) talks about "normalized" virtual addresses (ie. ELF virtual addresses) and the test`user_address_normalization_custom_so` explicitly checks that output address is equal to ELF symbol address (ie. ELF virtual address).
The test succeeds because for `libtest-so.so` file offsets and ELF virtual addresses are equal (because file offset and virtual address of the executable segment are equal).

The reason I am pointing this confusion is that for the use case of remote symbolication, file offsets are not very useful because file offset alone is not sufficient to perform remote symbolization in the case of split debug info:
* the first step of symbolization is to convert a file offset into an ELF virtual address, doing so requires knowing to which segment the file offset belongs to, and [adjusting](https://github.com/libbpf/blazesym/blob/v0.2.0-rc.1/src/elf/parser.rs#L882-L887) the file offset with the segment offset and segment virtual address
* but in split debug info, segment file offsets are not equal to the ones from the original binary (because keeping only debug info made all executable and data segments almost empty), and therefore if only split debug info is available it is not possible to recover the ELF virtual address from the file offset.

Would it be possible to have ELF virtual addresses as output of `Normalizer::normalize_user_addrs` ?

Here is the output of `readelf -lW /usr/local/bin/envoy` on envoy binary from docker image`envoyproxy/envoy-debug:v1.31-latest`:
```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000000040 0x0000000000000040 0x0002a0 0x0002a0 R   0x8
  INTERP         0x0002e0 0x00000000000002e0 0x00000000000002e0 0x00001b 0x00001b R   0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x179cc4c 0x179cc4c R   0x10000
  LOAD           0x179d000 0x00000000017ad000 0x00000000017ad000 0x26adb10 0x26adb10 R E 0x10000
  LOAD           0x3e4ab20 0x0000000003e6ab20 0x0000000003e6ab20 0x2910b8 0x2910b8 RW  0x10000
  LOAD           0x40dbbd8 0x000000000410bbd8 0x000000000410bbd8 0x0972f8 0xa60d18 RW  0x10000
  TLS            0x3e4ab20 0x0000000003e6ab20 0x0000000003e6ab20 0x000080 0x00262d R   0x20
  DYNAMIC        0x409abd0 0x00000000040babd0 0x00000000040babd0 0x000210 0x000210 RW  0x8
  GNU_RELRO      0x3e4ab20 0x0000000003e6ab20 0x0000000003e6ab20 0x2910b8 0x2914e0 R   0x1
  GNU_EH_FRAME   0x10bebd4 0x00000000010bebd4 0x00000000010bebd4 0x158494 0x158494 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0
  NOTE           0x0002fc 0x00000000000002fc 0x00000000000002fc 0x000044 0x000044 R   0x4
```

And the output of the same command on the split debug info generated with `objcopy --only-keep-debug /usr/local/bin/envoy envoy.dbg`:
```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000000040 0x0000000000000040 0x0002a0 0x0002a0 R   0x8
  INTERP         0x0002e0 0x00000000000002e0 0x00000000000002e0 0x000000 0x00001b R   0x1
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x000340 0x179cc4c R   0x10000
  LOAD           0x00d000 0x00000000017ad000 0x00000000017ad000 0x000000 0x26adb10 R E 0x10000
  LOAD           0x00ab20 0x0000000003e6ab20 0x0000000003e6ab20 0x000000 0x2910b8 RW  0x10000
  LOAD           0x00bbd8 0x000000000410bbd8 0x000000000410bbd8 0x000000 0xa60d18 RW  0x10000
  TLS            0x00ab20 0x0000000003e6ab20 0x0000000003e6ab20 0x000000 0x00262d R   0x20
  DYNAMIC        0x00ab20 0x00000000040babd0 0x00000000040babd0 0x000000 0x000210 RW  0x8
  GNU_RELRO      0x00ab20 0x0000000003e6ab20 0x0000000003e6ab20 0x000000 0x2914e0 R   0x1
  GNU_EH_FRAME   0x000340 0x00000000010bebd4 0x00000000010bebd4 0x000000 0x158494 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0
  NOTE           0x0002fc 0x00000000000002fc 0x00000000000002fc 0x000044 0x000044 R   0x4
```

This shows a binary for which `Offset` and `VirtAddr` of the executable segment are different, and this also shows that segments `Offset` in the split debug info are different.

**Comment by danielocfb** [comment]
Ah yes, parts of the documentation seem incorrect; as you said we always report file offsets from the normalization step. Will take another look at the tests as well. Thanks for pointing that out.

We used to report virtual addresses until 9f3c71344f9f6cd5d157aee13818390fc83541b8. Usage of file offsets allowed us to minimize the amount of work being performed on the "remote" end.

I *think* you should be able to post-process the output of the normalization to get virtual addresses as output instead. Basically, iterate over all the addresses, instantiate an [`ElfResolver`](https://docs.rs/blazesym/0.2.0-rc.1/blazesym/helper/struct.ElfResolver.html) on the corresponding path, and then use [`file_offset_to_virt_offset`](https://docs.rs/blazesym/0.2.0-rc.1/blazesym/symbolize/trait.TranslateFileOffset.html#tymethod.file_offset_to_virt_offset) to retrieve the virtual offset. Can you check whether that's feasible?

**Comment by danielocfb** [comment]
The above should have addressed everything. Otherwise speak up.

**Comment by nsavoire** [comment]
> The above should have addressed everything. Otherwise speak up.

The proposed solution works well for me, thanks for the quick help !
