### ISSUE TITLE
Unsoundness in C enum handling

### ISSUE THREAD

**Issue by d-e-s-o** [libbpf/blazesym#84]
The handling of all enums in our C API bindings is unsound. E.g.,

https://github.com/libbpf/blazesym/blob/9fe143a345f837c1dbec09530e8ec9f4a690c5f4/src/c_api.rs#L303-L310

C code could set any value, including those not representable by Rust. Discussed in many places (while also being common sense...), among others here: https://github.com/rust-lang/rust/issues/36927

**Comment by danielocfb** [comment]
So...after thinking about these potential issues some more I believe we should just live with them. If a user provides invalid enum variants through the C API that's on them and a bug in their code. We do not make any claims about being able to handle arbitrary wrong data, similar to how we would not identify a "broken" pointer (other than a NULL pointer; e.g., one that has been freed or just points into arbitrary memory). I am not sure we want to expend the energy to handle those invalid enum variants more gracefully. I am open to revisiting this issue in the future, but for now I am going to close it.
